<h1 style="text-align:center;">NumPy</h1>

In [2]:
import numpy as np

## Creating numpy arrays

In [ ]:
a = np.array([1,2,3])
print(type(a), a)   # Vector

<class 'numpy.ndarray'> [1 2 3]


In [11]:
# 2D and 3D
b = np.array([[1,2,3], [4,5,6]])    # Matrix
print(b)

c = np.array([[[1,2], [4,5]], [[3,4], [6,7]]])
print(c)    # Tensor

d = np.array([1,2,3], dtype=float)
e = np.array([1,2,3], dtype=complex)
f = np.array([1,2,3], dtype=bool)
print(d, e, f, sep='\n')

[[1 2 3]
 [4 5 6]]
[[[1 2]
  [4 5]]

 [[3 4]
  [6 7]]]
[1. 2. 3.]
[1.+0.j 2.+0.j 3.+0.j]
[ True  True  True]


In [14]:
# np.arange()

# Just like the classic range(), just float values would also be allowed

print(np.arange(3.4, 5, 0.1))

[3.4 3.5 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]


In [27]:
# np.reshape()

# very much used with arange() to convert the 1D array into some other dimension

print(np.arange(1, 10).reshape(3, 3))
print(np.arange(-10, 14).reshape(2, 2, 2, 3))
# ValueError if it is not shape-able

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[[-10  -9  -8]
   [ -7  -6  -5]]

  [[ -4  -3  -2]
   [ -1   0   1]]]


 [[[  2   3   4]
   [  5   6   7]]

  [[  8   9  10]
   [ 11  12  13]]]]


In [24]:
# np.zeros() and np.ones()

# np.zeros() ==> arg: shape, initialise an array with given shape with zereos
# np.zeros() ==> arg: shape, initialise an array with given shape with ones

# np.random.random() ==> arg: shape, initialise an array with given shape with random numbers

# default dtype is float, use can change it to dtype = int

print(np.zeros((2,3)))
print(np.ones((2,3), dtype=int))
print(np.random.random((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]]
[[0.29178644 0.43037574 0.98364207]
 [0.11299974 0.61525897 0.45271099]]


In [ ]:
# np.linspace() ==> Linear Space
# np.linspace() ==> arg: start, end, number of values... creates the points at equal distance

# 5 numbers between -10 and 10 such that they are equally spaced
print(np.linspace(-10, 10, 5))

[-10.  -5.   0.   5.  10.]


In [22]:
# np.identity()   ==> makes an identity matrix of given order 

print(np.identity(3))
print(np.identity(4))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Numpy Array Attributes

In [60]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)    # by default int64 (takes 8 bytes in memory, same as float)

In [ ]:
# ndim ==> returns number of dimensions

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [42]:
# shape

# can be intepreted as for n dim array: (...): first element how many (n-1) dim arrays, and then in each one of them, how many (n-2) dim arrays by following element and so on...

print(a1.shape) # (10,) as there're 10 0D arrays (single element) with no -1D arrays in it
print(a2.shape) # (3, 4) as there're 3 1D arrays with 4 0D arrays (single element) in it
print(a3.shape) # (2, 2, 2): there're 2 2D arrays, in each, 2 1D arrays and in each 2 elements

(10,)
(3, 4)
(2, 2, 2)


In [43]:
# size

# gives number of elements

print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [47]:
# itemsize

# gives size of each item in memory (in bytes)

print(a1.itemsize)  # each item 32bit int
print(a2.itemsize)  # each item 64bit float
print(a3.itemsize)  # each item 64bit int

4
8
8


In [46]:
# dtype

# gives the datatype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


## Changing DataType

In [50]:
# astype

print(a2.astype(np.int32))
print(a2)   # doesn't change the original array!

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


## Array Operations

In [64]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [58]:
# Scalar Operations

# arithmetic
print(a1*2)
pow(a1, 2)
print(a2>15)
print(a3==15)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[[[False False]
  [False False]]

 [[False False]
  [False False]]]


In [66]:
# Vector Operations

a1 ** a2    # correspondingly perform operations (ValueError if shapes are different)

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

## Array Functions

In [67]:
a1 = np.random.random((3,3))*100
a1

array([[90.30253867, 52.47819608, 79.50913538],
       [60.96300406, 88.20311857, 96.74917826],
       [ 2.05993118, 61.34675995,  3.63691132]])

In [72]:
# max/min/sum/prod

print(np.max(a1))
print(np.min(a1))
print(np.prod(a1))
print(np.sum(a1))

# 0 --> col; 1--> row 
print(np.max(a1, axis=0))   # Gives max col wise
# Applicable to all those functions

96.74917825778516
2.0599311844958668
90088743017324.16
535.2487734693657
[90.30253867 88.20311857 96.74917826]


In [ ]:
# mean/median/std/var 

np.mean(a1, axis=0)     # You got it!

array([51.10849131, 67.34269153, 59.96507499])

In [75]:
# trigo functions

np.sin(a1)

array([[ 0.71989309,  0.80094928, -0.82450058],
       [-0.95591015,  0.23626893,  0.59735104],
       [ 0.88273969, -0.99632973, -0.47531204]])

In [76]:
# dot product ==> same as matrix multiplication

a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(12, 24).reshape(4, 3)

np.dot(a2, a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [81]:
# log and exp 

print(np.log(a1))
np.exp(a2)

[[4.50316557 3.96039777 4.37587193]
 [4.11026719 4.47964232 4.57212184]
 [0.72267258 4.11654236 1.29113478]]


array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [84]:
# round/floor/ceil

# round => rounds off to nearest integer
# floor => GIF (round off to prev. integer (greatest lower integer bound))
# ceil => round off to next integer (lowest greater integer bound)

np.int32(np.ceil(a1))

array([[91, 53, 80],
       [61, 89, 97],
       [ 3, 62,  4]], dtype=int32)

## Indexing and Slicing

In [85]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [86]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
# indexing: exactly same as python list indexing

print(a1[-1])

9


In [92]:
print(a2[1][2])

# or simply

print(a2[1,2])
print(a2[1,0])

6
6
4


In [93]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [96]:
print(a3[1,0,1])
print(a3[0, 0, 0])
print(a3[0, 1, 0])

5
0
2


In [99]:
# Slicing : same as python list slicing

print(a1[2:5:2])
a2

[2 4]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
print(a2[0, :])     # first row, all columns
print(a2[:, 2])     # all rows, third columns
print(a2[1:, 1:3])
print(a2[::2, ::3]) # gets the corner items
print(a2[::2, 1::2])
print(a2[1, ::3])
print(a2[:2, 1::])

[0 1 2 3]
[ 2  6 10]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[4 7]
[[1 2 3]
 [5 6 7]]


In [110]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [115]:
print(a3[1])
print(a3[::2])
print(a3[0, 1])
print(a3[1, :, 1])
print(a3[::2, 0, ::2])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[3 4 5]
[10 13 16]
[[ 0  2]
 [18 20]]


## Iterating

In [116]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [117]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [118]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [121]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [125]:
# nditer ==> converts ndarray into 1dArray, and returns its iterator
print(np.array(np.nditer(a3)))

for i in np.nditer(a3):
    print(i)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping

In [ ]:
# Reshape

# Same as the np.reshape()

In [128]:
# Transpose
print(np.transpose(a2))

# or 

print(a2.T)
a2

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# ravel

# converts any ndarray into 1dArray

print(np.ravel(a2))

# or 

a2.ravel()

# Very much similar to nditer, but nditer is more memory efficient (Why?)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Stacking

Concate arrays over each other  
The shape of arrays should be same

In [130]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [131]:
np.hstack((a4, a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [132]:
# Vertical stacking

np.vstack((a4, a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting

Opposite of stacking  
hsplit --> splitting horizontally (vertical cut)  
vsplit --> splitting vertically (horizontal cut)

In [133]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [135]:
np.hsplit(a4, 4)    # has to be equal division (Otherwise ValueError)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [136]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [137]:
np.vsplit(a5, 3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]